vizorvr/patches

app.js, browser/index.html, browser/scripts/account-controller.js, browser/style/website.css, controllers/user.js, views/account/forgot.handlebars, views/account/login.handlebars, views/account/profile.handlebars, views/account/signup.handlebars, views/layouts/main.handlebars, views/layouts/spa.handlebars, views/partials/navbar.handlebars
Layout fixed, that linked accounts thing hidden, login/account/forgot password/signup headers are identical and content is centered. also from the editor, you can now open the signup modal from the login modal and vice versa without the modals overlapping. also fixed error messages for all of the POST operations on the user stuff, many of them weren’t showing up at all and some signup errors caused a break while in the editor. also changed the signup/login error messages for the editor to say sorry instead of “error happened” os. There’s some inline css in the layouts now cuz i didn’t bother taking out rules that might affect the editor too, so it needs a pass at some point.. but it all works and looks better (TM) now.
=> login, account, signup page fixes

browser/scripts/application.js, browser/scripts/renderer.js, gulpfile.js, package.json
Fixes #85. FQDN (if one exists in process.env.FQDN) is passed to renderer.js via gulp-preprocess, otherwise it defaults to create.vizor.io
=> Fixes #85. Pass FQDN to renderer.js

browser/plugins/graph.plugin.js, browser/plugins/input_proxy.plugin.js, browser/plugins/loop.plugin.js, browser/plugins/output_proxy.plugin.js, browser/plugins/register_local_read.plugin.js, browser/plugins/register_local_write.plugin.js, browser/scripts/application.js, browser/scripts/connection.js, browser/scripts/core.js, browser/scripts/graph.js, browser/scripts/node.js, browser/scripts/subGraphPlugin.js, browser/test/unit/plugins/helpers.js
Because the uid system was changed from integers to hash strings, this needs to be done to be able to load and paste older presets and graphs.
=> force uids and sids into strings; resolves #135

browser/scripts/graphStore.js, browser/scripts/node.js, browser/test/unit/graphStore.js, package.json
fixes #164
Node.reset() and Node.initialise() should really be called when the node is added to the graph, not when it is hydrated. This way, also nodes that are already hydrated (by instantiatePlugin()) will also get reset and initialised. 
Also change the order they are called, so that reset() can set the default values before initialise() calls plugin.state_changed().
=> move Node reset and init from Node.hydrate to GraphStore._uiNodeAdded

browser/index.html, browser/style/website.css
also fix line endings in website.css to unix...
the new css is this:
.frontpage-text-center {
text-align: center;
position: relative;
top: 50%;
transform: translateY(-50%);
}
=> center front page vizor logo vertically

browser/plugins/array_switch_modulator.plugin.js, browser/scripts/node.js
- set node dyn_input slots to inactive unless selected, resulting in skipping of rendering of those paths
- Node.js: cascade UI flow state upward
- early out in update_recursive if already rendered
=> ArraySwitch: don't render inactive inputs, resolves #332

browser/plugins/three_webgl_renderer.plugin.js, browser/scripts/worldEditor/worldEditor.js
when switching between experience and editor view
the 3d scene needs to be patched to contain the editor helper objects. if the scene had only static objects, this patching was not happening unless forcing a scene update when in the editor.
=> Fixes #604 - fix 3d editor grid redraw 

browser/plugins/three_uv_modifier.plugin.js, browser/plugins/url_texture_generator.plugin.js, browser/scripts/worldEditor/worldEditorOriginGrid.js
Instead send an extra update from the texture loader plugin once the texture has finished loading, with the correct image data.
Also remove some logging I accidentally committed to develop in a previous commit.
=> Fixes #611 - remove pending texture handling from uv modifier. 

browser/plugins/three_clickable_object.plugin.js
eventName was being ignored entirely
=> fixes #750 - use the correct event name on clickable object click

browser/scripts/application.js, browser/scripts/ui-core-statestore.js, browser/scripts/ui-core.js, browser/scripts/ui.js, views/editor.handlebars
- do not switch camera on build|program
- ui button hide all = hide floating panels
- tabs now controlled as per state rather than bootstrap (i.e. preset
tabs correctly disabled)
- return a realistic interpretation of “mode” (build|program) in
uistate
- fix erroneous click handling if assetsLib is null
=> ui refinements

browser/plugins/three_vr_camera.plugin.js, browser/vendor/three/VRControls.js
The problem with black rendering was that the rotation coming from webvr isn't a three.js quaternion but the code was trying to treat it as such and just producing a bunch of NaNs.
This also fixes some problems with the additive position & rotation offsets which weren't treated correctly before.
=> Resolves #870 - fix black rendering and additive position & rotation offsets

browser/scripts/application.js, browser/scripts/worldEditor/worldEditor.js
which detaches transform controls, so we don't end up with handles attached to nothing on delete
=> Resolves #874 - add onDelete() callback for worldEditor

browser/plugins/three_vr_camera.plugin.js
as otherwise the graph would ignore it's outputs and not re-evaluate nodes depending on them
This wasn't affecting the camera output itself, as three renders the scene with the correct camera anyway but any nodes in between that depended on these output values were ignored (Node.update_recursive() on line 397 skips any nodes that don't have their .updated flag set)
=> Resolves #900 - set camera state as updated on every frame

browser/plugins/three_vr_camera.plugin.js, browser/scripts/worldEditor/vrCameraHelperObject.js, browser/scripts/worldEditor/worldEditor.js
Removes camera flickering when doing 3d world edits
Also uses a single camera helper object instance rather than reconstructing on every update
=> Resolves #853 - fix camera matrix update ordering

browser/scripts/collapsible-select-control.js
moving the panel to a different position previously caused scrolltop()
calculations to be incorrect. #1020
=> fix bug in keyboard scrolling when presets panel moved

less/editor_shell.less, less/variables.less
header height was off by 2px resulting in extra blank space below switcher/name/breadcrumb row
see also #1015
=> fix header height

browser/plugins/three_vr_camera.plugin.js, browser/scripts/worldEditor/worldEditor.js
separate vr controls from the camera so that vr headset orientation doesn't change camera orientation in the world editor
=> Resolves #998 - fix vr camera orientation in the editor

browser/scripts/worldEditor/worldEditor.js
when framing selection to view, if no object is selected, frame the whole scene instead
=> Resolves #1113 - fix crash when framing a selection without a selection

browser/plugins/three_gaze_clicker.plugin.js
Changes to vr camera plugin broke the gaze cursor - position & quaternion were local to the headset so the cursor was rendered to the wrong place.
=> Resolves #1141 - fix gaze cursor after changes to vr camera

browser/plugins/three_group.plugin.js, browser/scripts/threeObject3dPlugin.js
1) don't store pivot in plugin state as this shouldn't be saved to the graph (yet)
2) when calculating the averaged center of objects, only use state.position rather than object3d.position which would also include the pivot's contribution and cause accumulation
=> Fix an incorrect calculation of group plugin's pivot

browser/plugins/three_webgl_renderer.plugin.js
configures vr manager to not display its own buttons
=> hide extra vr boilerplate buttons from player

browser/plugins/three_gaze_clicker.plugin.js
this was bugging because the gaze clicker count was set to a positive integer on the whole hierarchy below a gaze clickable object - when gazing at anything, the code (which I've fixed to prevent this) found the scene node in the root which had a positive gaze clicker count -> everything appeared to be clickable
=> Resolves #1107 - fix invalid gaze clicking outside the intended object

browser/vendor/three/webvr-manager.js
three.js r74 calls setSize() on every setPixelRatio() call, this causes the CardboardDistorter render target to be recreated on every frame even if it doesn't need to be recreated.
The better fix for this would be to not have to call setPixelRatio() on every frame but this will at least prevent the crash.
=> Resolves #1265 - prevent memory leak in webvr-manager

browser/scripts/ui-core.js, browser/scripts/worldEditor/worldEditor.js, views/patch_editor/help_shortcuts.handlebars
add a shortcut to moving the world editor camera to where the VR camera is
=> Resolves #1192 - Set editor camera to VR camera

browser/plugins/three_loader_scene.plugin.js, browser/scripts/loaders/modelLoader.js
bad migration to three.js r74 from my part, this fixes texture and mtl loading for OBJ + MTL loader path
=> Resolves #1300 - fix mtl loading

browser/plugins/three_vr_camera.plugin.js, browser/plugins/three_webgl_renderer.plugin.js, browser/scripts/application.js, browser/scripts/ui-core-statestore.js, browser/scripts/ui-core.js, browser/scripts/ui.js, browser/scripts/worldEditor/worldEditor.js, browser/scripts/worldEditor/worldEditorCameraSelector.js, views/patch_editor/help_shortcuts.handlebars
The World Editor now has a VR camera mode, in which it looks through the currently active VR Camera.
The World Editor is now active at all times apart from when both of these conditions are true:
1) the VR camera is active
2) the helper objects are invisible
Then the editor is disabled which should remove some of the editor overhead and give us the exact same result as a published graph
=> Resolves #1292 - Editing in vr cam

browser/scripts/application.js, browser/scripts/ui-core.js, browser/scripts/worldEditor/worldEditor.js, browser/scripts/worldEditor/worldEditorCameraSelector.js
'=' only works in bird's eye view
remember orthographicness when switching back from VR camera
In the ortographicness fix, essentially we now split the cameras into two categories ('birds eye' and 'vr') in the camera selector and pressing 'O' switches the camera into another one within the same category.
=> Resolves #1306, resolves #1307 - edit in vr cam fixes

browser/scripts/player.js
the player didn't stop playback when loading the new graph so the renderer would keep rendering while loading, before assets had been loaded
an alternative to this change would be to call Player.stop() which also cancels the anim frame
=> Resolves #1332 - no render until loaded

browser/scripts/threesixty.js, views/graph/show.handlebars
disables the automatic fadeout of the header and centre heading if loading for the first time. on subsequent plays (e.g. when a file is uploaded) that is reenabled.
=> 360-disable auto fade-out

browser/scripts/player.js
See #790 
This is a bug spread across a few areas. The webvr boilerplate polyfill tests for mousedown on the body to initiate a camera move, but at the time the renderer’s target is hidden (display:none) because we’re still showing a “loading” stage, and so its returned dimensions are 0x0.  However, the polyfill catches other things such as buttons that may be sitting on top of the render target. If a click is accompanied by a mouse move of just one pixel, this then breaks rendering, or more likely just the camera. A correct check would test whether a click before move has originated on the renderer’s dom element, but it seems the polyfill knows nothing about a renderer.
=> resolve an issue where the player might not start correctly

Dockerfile, bin/deploy.sh, gulpfile.js
- moves deploy.sh into bin/deploy.sh
- use the same deploy.sh for all containers
- requires new ENV variables PORT and NODE_ENV
- add new `golive` gulp step for running container
- add new provisioning step to push player into gridfs
=> add deploy.sh into repo, add provisioning step to deployment, fix player push

Dockerfile, README.md, app.js, bin/deploy.sh, browser/scripts/stores/peopleStore.js, browser/scripts/wschannel.js, controllers/graphController.js, lib/editorChannelServer.js, lib/serialNumber.js, modelRoutes.js, models/editLog.js, npm-shrinkwrap.json, package.json, test/controllers/graph.js, test/integration/multiuserEditing.js, test/integration/serialNumber.js, tools/migration/0.7.0/0.7.0-redis.js
- add pubsub channels via Redis
- store edit logs and chat in Redis instead of RethinkDB
- migration script to move edit logs & chat to Redis
- prepare to stop using RethinkDB altogether in the next release
=> use Redis as message broker and backend store for EditorChannelServer; resolves #1101

browser/scripts/worldEditor/worldEditor.js
node.outputs is all inputs, don't need to concatenate with dyn_outputs (which are slots, which was bad code)
=> Fix crash when selecting objects in the world editor

browser/vendor/three/EditorControls.js
Limit the zoom level to 10 cm and also allow the camera to zoom out of if below that limit.
No need to check if the mouse wheel zoom delta is bigger than current distance, because we won't go under it.
=> Limit the zoom level to 10 cm; resolves #1276

less/editor.less
slider plugin UI stretches correctly with node
=> resolve #1375 - stretch slider node ui correctly

browser/scripts/player-run.js
provides context to the message recipient, before change the message doesn't include enough information for the recipient to know what that variable's value is being delivered.
=> Include name of variable along with value

browser/scripts/ui-core-statestore.js, browser/scripts/ui-core.js, browser/scripts/ui.js
- makes modifier keys modify modify mode only temporarily until all modifier keys are released
- when any modifiers have changed but no modifiers are pressed, the default modify mode is restored.
- default modify mode is also applied when restoring state from persistent storage
=> resolves #1472; resolve 3d editor reverting to Move

browser/scripts/abstractAnimateValueOnTriggerPlugin.js
This had broken when we introduced pausing - this.abs_t was not up to date when the trigger occurred
broken behaviour:
animate_float_on_trigger is inactive (update_state not getting called)
trigger causes update_input, which sets this.startTime to this.abs_t (which is out of date, due to no update_state occurring for a while)
update_state gets called but now this.abs_t is > (this.startTime + this.duration) so it appears that nothing happened.
new behaviour:
the state and times are only ever updated in update_state, so everything stays in sync
=> Resolves #1490 - fix triggering animate_xxx_on_trigger

browser/scripts/ui-site.js, browser/scripts/ui/playerUI.js, browser/vendor/borismus/webvr-manager.js, browser/vendor/borismus/webvr-polyfill.js
resolves #1506 - wrong canvas dimensions on homepage
resolves #1504 - incorrect aspect ratio when switching between editor
cameras
fixes boilerplate regressions - canInitiateCameraMove and
getContainerDimensions now back where they were.
=> webvr boilerplate fixes

bin/deploy.sh, browser/scripts/application.js, browser/scripts/editorChannel.js, browser/scripts/wschannel.js, browser/test/unit/wsendpoint.js, controllers/graphController.js, test/integration/multiuserEditing.js, views/editor.handlebars
- for production, use WSS_HOST=ws.vizor.io
- for dev hosts, use NODE_ENV=dev but WSS_SECURE=true
- for dev hosts with CloudFlare, use WSS_SECURE=false and WSS_HOST=ws.xxx.vizor.lol
- for localhost, default to non-secure localhost WS
=> fixes to Web Socket connection setup

browser/scripts/webVRAdapter.js
resolves #1612 #1613 
these also seem to be bugs in Chrome/iOS due to excessive resizing for the purposes of its own UI
=> stagger resizing

browser/plugins/three_webgl_texture_renderer.plugin.js
If render to texture was used in a graph, this resulted in the render viewport resizing to 50% width on every frame when in VR.
=> Resolves #1648 - fix incorrect viewport resizing when using render to texture

browser/plugins/url_stereo_cubemap_generator.plugin.js
On Samsung S6 + chrome, drawImage straight from image will mess up dimensions. Use an intermediate canvas to first draw the full image into, and then draw from that canvas to the smaller images.
=> use an intermediate canvas to work around chrome drawImage bug

browser/plugins/three_loader_scene.plugin.js, browser/plugins/url_stereo_cubemap_generator.plugin.js, browser/scripts/ui-site.js, browser/scripts/ui.js, browser/scripts/ui/playerUI.js, browser/scripts/util.js, browser/scripts/webVRAdapter.js
Fix stereo cubemaps for iOS. Android needs an intermediate texture and ios doesn't so split these out into separate code paths.
=> Resolves #1718 - fix iOS cubemaps

app.js
this allows using the same cookie for vizor.io and 360.vizor.io
=> use actual domain as cookie domain from FQDN

views/partials/breadcrumb.handlebars
this is due to a previous bug in handlebars where {with} within an
{each} had the wrong context. i’ve checked for other instances of
similar bugs and did not find any.
=> fix #1775 default breadcrumb separator

browser/plugins/three_vr_camera.plugin.js
"the camera settings might be ever so slightly different regarding back plane distance so that it changes when you switch overlays off. this fixes that (unless you override the far plane distance in the vr camera, in which case you’re out of luck)"
=> match world editor and vr camera far planes

services/assetService.js
the issue was a default limit of 20 in `AssetService.find()`
=> fix patches list missing most objects

browser/scripts/application.js, browser/scripts/ui-breadcrumb.js, browser/scripts/ui-core-statestore.js, browser/scripts/ui-core.js, browser/scripts/ui.js, browser/scripts/ui/uiAbstractProperties.js, browser/scripts/ui/uiPropertiesNode.js, browser/scripts/ui/uiPropertiesObj3d.js, browser/scripts/worldEditor/worldEditor.js, browser/test/unit/breadcrumb.js
- resolves #1890 - revert `tab` behaviour to toggle patch editor to its last active graph
- resolves #1891 - `shift+tab` to open patch editor to inside of selected object
- resolves #907 - show vr camera in breadcrumb
- resolves #1901 - refresh breadcrumb if node renamed by concurrent user
- resolves #1900 - breadcrumb shows duplicated entries
- fixes #1902 - mixpanel tracking program->build many times over
- refines breadcrumb behaviour when selecting grouped objects
- also adds a temporary fix for error on deleting of grouped objects from world editor
=> tab to editor and breadcrumb fixes

app.js, browser/plugins/url_audio_buffer_generator.plugin.js, browser/scripts/file-select-control.js, browser/scripts/loaders/audioBufferLoader.js, browser/scripts/util.js, browser/vendor/three/OBJLoader.js, controllers/assetController.js, lib/streamFile.js, modelRoutes.js, package.json
- Support switching between ogg and m4a (iOS) depending on platform. To use this, upload the audio as ogg *and* m4a with the same name, and iOS/Safari will use the m4a.
=> Release 20170131 - v0.15.1: Support audio on Safari and iOS

browser/scripts/vizor2Teaser.js, views/vizor2Teaser.handlebars
The form submission has to be delayed to track it. Otherwise, the browser might cancel the requests to Mixpanel and/or Google Analytics APIs.
I used 300ms, because that's the value that Mixpanel JS API uses by default: https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.track_forms
Tested in latest Chrome, Safari and Firefox on Mac.
=> Vizor2 teaser form submission tracking

app.js
Serve Patches home page when accessing `/` from patches.vizor.io. Otherwise, serve the teaser page when accessing `/`.
=> Make Vizor 360 teaser page the default home route

browser/plugins/ga_pageview.plugin.js, browser/plugins/google_analytics.plugin.js, browser/plugins/plugins.json, browser/scripts/node-ui-enum.js, documentation/browser/plugins/ga_pageview.md, documentation/browser/plugins/google_analytics.md, views/server/partials/gtm.handlebars
Two new plugins: plugin for setting a custom Google Analytics Tracking ID, will create a `customTracker`; a plugin for sending `pageview` events as hashes under the experience URL.
=> Allow sending custom GA pageviews from graphs

browser/scripts/ui/playerUI.js, browser/scripts/webVRAdapter.js
- webVRAdapter waits longer until orientationchange transition is well complete before resizing the viewport
- playerUI waits until the orientationchange transition is complete before resizing document.body (allowExtraHeightOnLandscape) - this only affects iphone/ipodtouch
- webVR adapter no longer binds on orientationchange on iOS, as that emits a resize too.
all in all - slower to respond, but more stable and one less handler.
tested on iOS 10.3.1, iPad Pro 9.7"
=> fix orientationchange ipad issues

views/patch_editor/help_shortcuts.handlebars
Modified help text so each shortcut is on it's own row, aligned shortcut keys with text,
added Handy Keys (0-9) with accurate descriptions.
This will address #1915 by @mattatgit
=> Tweaked text, added 0-9 hotkeys

documentation/browser/plugins/graph.md, documentation/browser/plugins/three_scene.md
As regards @mattatgit 's #819 issue, tooltips for Scene and Nested Patch have been updated with "better info".
NOTE: these are works in progress, if Matt likes them, we could merge these in. Still need to figure out how to force the next row in these descriptions, probably not <br>
=> Modified Scene and Nested Patch popup help

documentation/browser/plugins/const_float_generator.md, documentation/browser/plugins/float_display.md, documentation/browser/plugins/graph.md, documentation/browser/plugins/input_proxy.md, documentation/browser/plugins/knob_float_generator.md, documentation/browser/plugins/multiply_modulator.md, documentation/browser/plugins/output_proxy.md, documentation/browser/plugins/slider_float_generator.md, documentation/browser/plugins/toggle_button.md, documentation/browser/plugins/vector.md
Here's keyboard shortcut stuff added to each and every of the 10 shortcuts (Handy Keys, remember them?).
modified:
Input: 1 (( input_proxy.md ))
Nested patch: 2 (( graph.md ))
Slider: 3 (( slider_float_generator.md ))
Number: 4 ((const_float_generator.md ))
Float: 5 (( float_display.md ))
Multiply Number 6 (( multiply_modulator.md )) 
XYZ to Vector: 7 (( vector.md ))
Toggle: 8 (( toggle_button.md ))
Knob: 9 (( knob_float_generator.md ))
Output: 0 (( output_proxy.md ))
next step: find someone to modify CSS so the keyboard shortcut text looks like what @mattatgit suggested: 
> Instead of white should be darker blue
> bit lighter than background
> number same colour as other text. 
> #3F4963 "this is for the keyboard shortcut key name box background"
=> "Keyboard shortcut" added to descriptions

views/server/partials/userpage/nav.handlebars
@mattatgit was requesting that "Your Files" should read "Your Projects" - went in and found that it reads "Projects" - switched to "Your Projects". Check https://github.com/vizorvr/vizor/issues/1871
#1871
=> Projects -> Your Projects

app.js, browser/plugins/three_webgl_renderer.plugin.js, browser/scripts/embed.js, browser/scripts/player.js, browser/scripts/ui/playerUI.js, browser/scripts/webVRAdapter.js, browser/vendor/borismus/webvr-polyfill.js, browser/vendor/three/VREffect.js, browser/vendor/three/three.js, views/graph/show.handlebars, views/server/partials/home/homeHero.handlebars
note PR base branch
further fixes:
blackscreen in Hungry Spirits (render-to-texture plugin and Three messing up the canvas)
tested in:
- desktop: Safari, Firefox, Chrome
- mobile: iOS iPhone 6S, iPhone SE, Android Samsung S6
- embed: all of the above
- for orientation: landscape and portrait on standalone and embedded
- for devicemotion: all mobile, standalone and embedded
needs further testing in MS Edge
notes:
- the polyfill now implements its own method to receive messages in iframe, which seems to be missing orientationchange processing. Switching orientation in an iframe didn't work for me. Additionally, with the latest version of Android, devicemotion and orientation events seem to need proxying just as on iOS.
- restored event on VR instructions showing and hiding
- restored …
=> fix polyfill

browser/test/integration/helpers.js
```
bash-3.2$ mocha browser/test/integration/init-revolver.js
Initialisation together with if statements
reset 1 1 1
reset 1 1 1
THREE.Object3D.add: object not an instance of THREE.Object3D. undefined
THREE.Object3D.add: object not an instance of THREE.Object3D. undefined
✓ inits the correct number (269ms)
1 passing (443ms)
```
=> mock window.dispatchEvent to fix tests

browser/scripts/webVRAdapter.js, browser/test/functional/support/action/openEditor.js, browser/test/functional/support/action/waitForEditor.js
fix #2078 
background: `devicePixelRatio` when `isPresenting` is 1 and canvas sizing must be determined from the actual `renderWidth` and `renderHeight` parameters for each eye.
for the GearVR Samsung S6 `renderWidth` and `renderHeight` equal 1024, but the display is 2560x1440, so some upscaling is forced.
I experimented with calculating devicePixelRatio instead in order to achieve higher quality image, but got inconsistent results across the range VR/iOS/Android-cardboard.
tested on: 
- macOS: desktop (Safari), 
- iOS: magic window & polyfilled VR
- Android: magic window, polyfilled VR, GearVR/Oculus browser
=> fix resolution in GearVR/Oculus browser

browser/vendor/three/OBJLoader.js
This is a bug that slipped in the last release. When decimating objects in Blender, they are left with `l` lines in the .obj that are out of place, making the loader attempt to put two kinds of geometries in the same object. This works around that bug by simply ignoring the `l` lines altogether, like the previous version of the loader did.
=> Hack OBJLoader to work with machinedrum/ocean-of-thought objs

browser/help/introduction.html, browser/scripts/threesixty.js, views/partials/account/signup.handlebars, views/server/partials/home/_footer.handlebars
This changes all GoogleDocs links to HubSpot links for Terms of Service & Privacy Policy.
=> Patches TOS&PP link changes
