vizorvr/patches

- browser/plugins/array_switch_modulator.plugin.js
- browser/plugins/audio_gain_modulator.plugin.js
- browser/plugins/from_mesh_custom_shader.plugin.js
- browser/plugins/switch_modulator.plugin.js
- browser/scripts/commands/graphEditCommands.js
- browser/scripts/graphApi.js
- browser/scripts/graphStore.js
- browser/scripts/node.js
- browser/scripts/shader-editor.js
- browser/test/unit/graphShapes.js
- browser/test/unit/node.js
- browser/test/unit/paste.js
- views/ui/shader.handlebars
- added AddSlot, RemoveSlot GraphEditCommands
- made ArraySwitch, ShaderEditor, FromMeshCustom, AudioGainModulator, SwitchModulator plugin slot additions/removals undoable
> Undoable dynamic slot additions

- browser/scripts/collapsible-select-control.js
- less/core.less
> generic bind drag and dropping from preset list

- browser/scripts/application.js
- browser/scripts/editorChannel.js
- browser/scripts/peopleStore.js
- browser/scripts/wschannel.js
- browser/style/less.css
- browser/test/unit/graphShapes.js
- browser/test/unit/paste.js
- browser/test/unit/peopleStore.js
- less/core.less
- lib/editorChannelServer.js
- package.json
- views/layouts/spa.handlebars
adds PeopleStore that keeps track of everyone's mouse positions, active graphs, colors, and mouse clicks
> Mouse position, click, and active graph mirroring, resolves #108

- app.js
- browser/scripts/application.js
- browser/scripts/editConnection.js
- browser/scripts/editorChannel.js
- browser/scripts/peopleManager.js
- browser/scripts/peopleStore.js
- browser/scripts/player.js
- browser/scripts/treeview.js
- browser/style/less.css
- browser/test/unit/peopleStore.js
- less/build.less
- less/core.less
- less/people.less
- lib/editorChannelServer.js
- test/unit/editorChannelServer.js
- views/editor.handlebars
- views/layouts/spa.handlebars
- views/partials/peopleMenu.handlebars
Follow user: List of users in People tab, click to follow user, click again to unfollow
Other changes:
- add E2.app.growl() method for showing messages
- stop handling ctrl/cmd-l
- add userId to session cookie
- make the server know about active graph, followers
> Follow user, resolves #109

- browser/plugins/array_switch_modulator.plugin.js
- browser/plugins/audio_gain_modulator.plugin.js
- browser/scripts/editConnection.js
- browser/test/unit/editConnection.js
- also pick up new slots in arraySwitch
> fix audio player preset error, fixes #167

- browser/plugins/from_mesh_custom_shader.plugin.js
- browser/scripts/connection.js
- browser/scripts/graphStore.js
- browser/scripts/node.js
- browser/scripts/shader-editor.js
- browser/test/unit/connection.js
- browser/test/unit/node.js
- Mirror Shader edits
- fix Connection dt equality check
- node.setPluginState(), Node#pluginStateChanged
> Mirror Shader edits, resolves #183. Also a fix to Connection validity check.

- browser/scripts/application.js
- browser/scripts/editorChannel.js
- browser/scripts/event-emitter.js
- browser/scripts/wschannel.js
- lib/editorChannelServer.js
- test/integration/multiuserEditing.js
Also change EventEmitter to a proper one
> fix event listener binding on leave/join, add test, fixes #184

- browser/scripts/application.js
- browser/style/less.css
- browser/vendor/js.cookie.min.js
- less/core.less
- less/people.less
- views/layouts/spa.handlebars
- also fix location of remote-mouse-pointer style (should be in people.less)
> show first-time dialog if no vizor cookie, resolves #209

- app.js
404 will display the error string in min layout. Later on we could replace this with an actual error layout/page.
> fix the 404 error page to actually show the error

- app.js
decided to do this in the app instead of nginx
> redirect all create urls to vizor.io, resolves #212

- browser/plugins/annotation.plugin.js
- browser/plugins/color_picker.plugin.js
- browser/plugins/const_float_generator.plugin.js
- browser/plugins/const_text_generator.plugin.js
- browser/plugins/knob_float_generator.plugin.js
- browser/plugins/slider_float_generator.plugin.js
- browser/plugins/toggle_button.plugin.js
- browser/plugins/url_texture_generator.plugin.js
- browser/scripts/plugin.js
- adds most used plugins to use pluginStateChange event directly
- fallback in Plugin.js to do that with state_changed(ui)
> update plugin ui`s on plugin state change, fixes #219, #199, #207, #221, #215

- browser/index.html
- browser/scripts/renderer.js
- browser/style/website.css
homepage fixes, fixed renderer fullscreen to sniff from screen when inside editor and from window when outside app
> homepage fix

- app.js
- lib/gridfs-storage.js
- test/unit/gridfs-storage.js
Add support for partial http content requests
> Issue #171 - Video player doesn't loop successfully

- browser/scripts/application.js
- browser/style/less.css
- less/core.less
- less/variables.less
- views/editor.handlebars
- views/layouts/editor.handlebars
1. top menu bar design
2. found round corners bug on hover, added 1 more commit.
> Top nav bar

- browser/scripts/application.js
- browser/style/less.css
- less/core.less
- less/variables.less
- views/editor.handlebars
- views/layouts/editor.handlebars
Reverts vizorvr/vizor-create#366
> Revert "Top nav bar"

- browser/plugins/three_material_modifier.plugin.js
- browser/test/unit/plugins/material_modifier.js
remove invalid characters and deal with initial state where materials only come in late during object loading taking time
> material override bugfixes

- browser/plugins/plugins.json
- browser/plugins/three_screen_space_transform_extractor.plugin.js
This will allow us to place stuff in screen space
> add a plugin for extracting transformations out of a camera

- browser/plugins/array_function.plugin.js
- browser/plugins/array_get.plugin.js
- browser/plugins/array_length.plugin.js
- browser/plugins/plugins.json
- browser/plugins/three_mesh.plugin.js
- browser/plugins/variable_local_write.plugin.js
- browser/scripts/abstractThreeMeshPlugin.js
- browser/scripts/application.js
- browser/scripts/graph.js
- browser/scripts/subGraphPlugin.js
- browser/scripts/variables.js
- browser/style/less.css
- browser/test/integration/array_function.js
- browser/test/unit/plugins/array_function.js
- less/core.less
- package.json
A loop that generates an array with a graph, using input variable `index` for the graph and output variable `item` from the graph to generate an array
*This will break existing patches using three_mesh*
> Array function, resolves #307

- browser/plugins/plugins.json
- browser/plugins/three_environment_settings.plugin.js
- browser/plugins/three_scene.plugin.js
- browser/scripts/core.js
- browser/scripts/datatypes/environmentSettings.js
- browser/scripts/node.js
- views/layouts/editor.handlebars
and fix bug in node.js which was converting THREE.Vector3 to arrays...
> add fog settings for scene

- browser/scripts/editorChannel.js
- lib/editorChannelServer.js
- test/integration/multiuserEditing.js
to improve multiuser test flakiness
> add optional acknowledgements to messages

- app.js
- browser/data/graphs/default.json
- browser/scripts/application.js
- browser/scripts/editorChannel.js
- browser/scripts/plugin-manager.js
- controllers/graphController.js
- lib/editorChannelServer.js
- models/editLog.js
- test/fixtures/graph.json
- test/integration/multiuserEditing.js
- test/integration/upload.js
- views/editor.handlebars
- let the client know whether the document has edits
- connect Rethink at server startup
> fix loading default graph

- browser/scripts/application.js
- browser/style/less.css
- less/build.less
- less/chat.less
- less/collapsible-select-control.less
- less/core.less
- less/libraries.less
- less/people.less
- less/scrollbars.less
- views/editor.handlebars
- views/partials/peopleMenu.handlebars
- views/presets/presets.handlebars
> Scrollbars for assets, presets, chat

- browser/scripts/account-controller.js
- browser/scripts/application.js
- less/build.less
- less/core.less
- less/modals.less
- less/variables.less
- views/account/login.handlebars
- views/editor.handlebars
- views/layouts/editor.handlebars
- views/partials/svgSprite.handlebars
also affected general bootbox messages like first time message. now with new design too.
> Sign in modal with effects

- browser/plugins/three_uv_modifier.plugin.js
the texture wasn't getting updated if it was already loaded
> set dirtiness correctly

- browser/scripts/application.js
- browser/scripts/editorChannel.js
- browser/scripts/wschannel.js
- test/integration/multiuserEditing.js
change wschannel url to not use a ws.-prefix if not running in release mode
> wschannel url change

- browser/plugins/three_webgl_renderer.plugin.js
- browser/scripts/player.js
and don't initialise object picking if we're in player mode
> Fixes #495 - add a player implementation of isVRCameraActive()

- browser/plugins/three_webgl_texture_renderer.plugin.js
as if left behind, the render to screen would splat over this data and cause visual corruption
> Fixes #478 - clear three's current render target after rendering to a texture

- browser/scripts/account-controller.js
- browser/scripts/application.js
- browser/scripts/file-select-control.js
- browser/scripts/ui.js
- browser/scripts/userpage.js
- less/collapsible-select-control.less
- less/core.less
- less/file-select-control.less
- less/libraries.less
- views/account/account.handlebars
- views/account/reset.handlebars
- views/editor.handlebars
- views/filebrowser/generic.handlebars
- views/filebrowser/graph.handlebars
- views/filebrowser/preset.handlebars
- views/filebrowser/save-frame.handlebars
- views/filebrowser/texture.handlebars
- views/partials/svgSprite.handlebars
account popup, presets list, fixes
> account and fixes

- browser/plugins/three_webgl_renderer.plugin.js
- browser/scripts/core.js
- browser/scripts/worldEditor/worldEditor.js
Better camera & transform controls - can move the camera even if an object is selected
Add helper objects for lights in the editor view
> Develop 3d edit

- browser/data/graphs/default.json
- browser/plugins/plugins.json
- browser/plugins/three_loader_model.plugin.js
- browser/plugins/three_loader_scene.plugin.js
- browser/scripts/abstractThreeLoaderObjPlugin.js
- browser/scripts/abstractThreeMeshPlugin.js
- browser/scripts/threeObject3dPlugin.js
- browser/scripts/worldEditor/worldEditor.js
- browser/vendor/three/SceneLoader.js
- browser/vendor/three/TransformControls.js
- browser/vendor/three/three.js
- gulpfile.js
- views/layouts/editor.handlebars
adding a scene loader (for three.js)
bugfixing obj loader process
> Develop scene loader

- vendor/three/fbx/LICENSE
- vendor/three/fbx/README.md
- vendor/three/fbx/convert_to_threejs.py
Requires Autodesk FBX Python SDK (http://usa.autodesk.com/adsk/servlet/pc/item?siteID=123112&id=10775847). Tested with FBX SDK 2015.1
Tested with Python 2.7.10
> add a slightly modified version of 3ds/fbx -> json converter

- browser/scripts/application.js
- browser/scripts/file-select-control.js
- browser/scripts/movable.js
- browser/scripts/ui.js
- browser/scripts/userpage.js
- browser/user.html
- less/build.less
- less/modals.less
- less/userpage.less
- less/variables.less
- views/editor.handlebars
- views/filebrowser/publishModal.handlebars
- views/filebrowser/upload.handlebars
pan-drag bug fix.
2 view buttons.
userpage.
upload modals styles.
no harm to publish.
> recover features lost during newui develop merge

- browser/scripts/account-controller.js
- views/account/signup.handlebars
fixed "Uncaught ReferenceError: user is not defined @ account-controller.js:95"
> user error fix

- browser/scripts/collapsible-select-control.js
> Patches lib: promote exact match to the top of search results

- browser/plugins/array_get.plugin.js
- browser/plugins/array_switch_modulator.plugin.js
- browser/plugins/convert_vector_xyz_modulator.plugin.js
- browser/plugins/plugins.json
- browser/plugins/runtime_event_write.plugin.js
- browser/plugins/three_clickable_object.plugin.js
- browser/plugins/three_gaze_clicker.plugin.js
- browser/plugins/three_mesh.plugin.js
- browser/plugins/three_object3d_attribute_extractor.plugin.js
- browser/scripts/worldEditor/worldEditor.js
- browser/test/integration/runtimeEvents.js
all found for developing a game
> Fixes #557 - gaze clicker and various other fixes 

- browser/scripts/application.js
- browser/scripts/ui.js
for now - part of E2.app.path excluding 'username/'
> add graph name to page title if logged in

- browser/scripts/collapsible-select-control.js
- browser/scripts/preset-manager.js
- browser/scripts/ui-core.js
- browser/scripts/ui.js
- less/libraries.less
- views/editor.handlebars
current lib expand on non-empty search focus, click on search result = collapse floating boxes under.
> lib expand on search focus, ui collapse on preset click

- browser/scripts/ui.js
- views/editor.handlebars
disables irrelevant buttons in top bar for each viewmode
> toggle buttons "disabled" for different viewmodes.

- browser/scripts/application.js
- browser/scripts/ui-core.js
- browser/scripts/ui.js
- less/modals.less
- less/patch_editor.less
press “\” to view source when patch editor is active.
> view source #583

- browser/scripts/application.js
- browser/scripts/ui-core.js
> fix for UI keyboard shortcuts stop working

- less/build.less
- less/playerpage.less
- views/graph/show.handlebars
- views/layouts/player.handlebars
- views/partials/svgSprite.handlebars
> interim player page; resolves #675

- browser/scripts/application.js
- browser/scripts/collapsible-select-control.js
- browser/scripts/movable.js
- browser/scripts/ui-core.js
- browser/scripts/ui.js
- browser/vendor/three/webvr-polyfill.js
- less/patch_editor.less
- views/editor.handlebars
save/restore UI state
constrain UI settings. also 
fixes #653 
fixes #654 
fixes #655
> PR serialise and store/recall UI settings; resolves #525

- browser/plugins/slider_float_generator.plugin.js
- browser/scripts/editorChannel.js
- browser/scripts/graphStore.js
- browser/scripts/plugin.js
- lib/editorChannelServer.js
uiPluginTransientStateChanged allows sending transient, realtime plugin
state values
> uiPluginTransientStateChanged for Slider; resolves #586

- browser/patchTemplates/scene.hbs
- browser/plugins/three_scene.plugin.js
- browser/scripts/application.js
- browser/scripts/ui-upload.js
- browser/scripts/worldEditor/worldEditor.js
copy, paste and delete work in the editor
first pass, this is likely to require more work & a better design
> copypaste in 3d editor, resolves #720

- browser/plugins/plugins.json
- browser/plugins/three_material_extractor.plugin.js
> add a material extractor plugin, resolves #776

- browser/scripts/abstractThreeLoaderObjPlugin.js
> calculate vertex normals if they don't exist, resolves #777

- browser/data/graphs/default.json
- browser/plugins/three_vr_camera.plugin.js
- browser/presets/_template-360-photo.json
- browser/presets/_template-basic-vr-scene.json
- browser/vendor/three/VRControls.js
also remove FOV from presets, as the default fov is already 90 and shouldn't really be messed with, especially in VR where this is overridden anyway and
> add a rotation input to vr camera (additive, like position), resolves #758

- browser/scripts/application.js
results aren't always optimal. this can be improved and probably needs much further work once we render the graph in gl.
> first pass autolayout, resolves #808

- browser/plugins/three_scene.plugin.js
ignoring the connected-status of the last slot and possibly adding a slot at -1
> the previous slot adding logic had some subtle errors

- browser/vendor/three/webvr-manager.js
- browser/vendor/three/webvr-polyfill.js
Updated webvr-manager and webvr-polyfill to latest. Still doesn't fix ios fullscreen, however this should fix the problems people are seeing on Android 6.0 on Nexus 5.
> New webvr boilerplate, resolves #779

- browser/scripts/application.js
- browser/scripts/worldEditor/vrCameraHelperObject.js
- browser/scripts/worldEditor/worldEditor.js
> Resolves #835 - match vr camera to world editor

- browser/scripts/application.js
- browser/scripts/editConnection.js
- browser/scripts/node.js
- browser/scripts/stores/graphStore.js
- browser/scripts/worldEditor/worldEditor.js
- call onLocalConnectionChanged() from WorldEditor
- remove promise from EditConnection
- call onLCC from EditConnection
- remove connection specific events from GraphStore
> add onLocalConnectionChanged, fixes #869

- browser/plugins/format_string_float.plugin.js
- browser/plugins/variable_local_read.plugin.js
- browser/plugins/variable_local_write.plugin.js
- browser/scripts/variables.js
this avoids the variable emitting null on the first frame, because now its datatype is set correctly.
> fix variable datatypes on init

- browser/plugins/convert_camera_matrices.plugin.js
- browser/plugins/three_gaze_clicker.plugin.js
- browser/plugins/vector_to_screenspace.plugin.js
- browser/plugins/vector_transform.plugin.js
- browser/vendor/three/TransformControls.js
so that a valid view matrix can be extracted from a three.js camera.
also fixes rotation in 3d editor of an additive rotation
> Resolves #905, #914, #915 - fix camera matrix operations

- browser/scripts/editorChannel.js
Snapshot already includes the edit.
> don`t snapshot *and* write to channel on first edit; fixes #831

- browser/scripts/worldEditor/worldEditor.js
(that would be rendered at current time if we weren't in the world editor), not the selected camera
> pressing = will now place the current camera 

- browser/vendor/three/three.js
This allows objects which fail to load some of the textures, still to finish loading and not just hang there indefinitely.
> Changes corresponding to three.js PR# 7801

- app.js
- browser/data/graphs/default.json
- browser/plugins/plugins.json
- browser/plugins/stereo_cube_map.plugin.js
- browser/plugins/three_cube_material.plugin.js
- browser/plugins/url_stereo_cubemap_generator.plugin.js
- browser/presets/_add_stereo_cubemap.json
- browser/presets/presets.json
- browser/scripts/file-select-control.js
- browser/scripts/loaders/imageLoader.js
- browser/scripts/threeObject3dPlugin.js
- browser/vendor/three/three.js
- controllers/assetController.js
- controllers/graphController.js
- controllers/imageController.js
- lib/imageProcessor.js
- modelRoutes.js
- services/assetService.js
- test/integration/graph-save.js
- test/integration/upload.js
- test/unit/imageProcessor.js
- tools/test-runner.js
- views/filebrowser/upload.handlebars
1) add a cubemap material
2) add a stereo view selector input to object3ds
3) add a preset using a separate path for left and right eye cubemaps (Add Objects / Stereo Cubemap)
> Cubemap workflow

- browser/scripts/application.js
- browser/scripts/collapsible-select-control.js
- browser/scripts/preset-manager.js
- browser/scripts/ui.js
- browser/test/unit/collapsibleSelectControl.js
- browser/test/unit/paste.js
- less/collapsible-select-control.less
- less/core.less
- less/variables.less
- views/presets/presets.handlebars
- views/presets/results.handlebars
resolve:
- style as per design #843
- fix issue where dragging over a panel was closing the wrong panel
#884
- fix issue where switching tabs would result in an empty list #944
- fix keyboard scrolling in search results #1003
- fix Y offset in dragging presets&nodes out #1004
- fix paste offset #1002
> presets panel refinements

- browser/scripts/shader-editor.js
- less/editors.less
- views/editor.handlebars
shader editor sizes between 24 and 40 lines (was previously fixed at 50)
> fix shader editor sizing #970

- browser/plugins/stereo_cube_map.plugin.js
it's off the menus but old graphs with otoy urls load ok now
> revert old stereo_cube_map plugin back for backwards compatibility

- browser/plugins/mouse_wheel_generator.plugin.js
Resolve the wheelDelta from behind mousewheel event's originalEvent
> Resolves #1031 - fix mouse wheel emitter

- browser/scripts/worldEditor/worldEditor.js
remove unnecessary allocations from world editor and instead only create helper objects for things that have changed
> Resolves #1045 - memory leak fix

- browser/plugins/three_scene.plugin.js
readd an accidentally removed operation for setting the fog for scene
> Resolves #1006 - fix fog

- browser/plugins/animate_value_on_trigger.plugin.js
- browser/plugins/array_blend_modulator.plugin.js
- browser/plugins/plugins.json
- browser/presets/_animate-on-trigger.json
- browser/scripts/blendFunctions.js
- browser/scripts/core.js
- browser/test/unit/blendFunctions.js
- gulpfile.js
- views/layouts/editor.handlebars
two new plugins:
Animate Between Inputs
Animate On Trigger
> Develop animation plugins

- browser/scripts/application.js
- browser/scripts/util.js
- browser/scripts/worldEditor/worldEditor.js
- browser/scripts/worldEditor/worldEditorCameraSelector.js
- browser/scripts/worldEditor/worldEditorOrthographicCamera.js
- browser/scripts/worldEditor/worldEditorPerspectiveCamera.js
- browser/vendor/three/EditorControls.js
- gulpfile.js
- views/layouts/editor.handlebars
(shift+)X/Y/Z switch between x/y/z viewpoints
O to switch between orthographic and perspective camera
> orthographic cameras

- browser/plugins/plugins.json
- browser/plugins/three_hemisphere_light.plugin.js
- browser/plugins/three_spot_light.plugin.js
- browser/presets/_add-hemisphere-light.json
- browser/presets/presets.json
- browser/scripts/worldEditor/worldEditor.js
spot lights are a little problematic so left them out of the presets list
> Resolves #1083 - add hemisphere and spot lights

- controllers/graphController.js
- views/graph/show.handlebars
> Revert "Display graph name in player view in human readable form; resolves #1036"

- browser/scripts/ui-core.js
- browser/scripts/ui.js
allow objects/patches tab to switch build mode
> resolve #1094 - switch build/program from objects/presets panel tab

- less/playerpage.less
- views/graph/show.handlebars
corrects header behaviour on ios
> fix player header fadeout on touchscreen

- browser/plugins/three_loader_scene.plugin.js
- browser/plugins/three_scene.plugin.js
- browser/plugins/three_vr_camera.plugin.js
- browser/plugins/url_texture_generator.plugin.js
- browser/scripts/ui-upload.js
- browser/scripts/worldEditor/worldEditor.js
- browser/vendor/three/TransformControls.js
- browser/vendor/three/webvr-manager.js
alt-dragging quickly in the editor no longer moves the original objects and models loaded with three_scene_loader can now be properly copied
> Resolves #1110, Resolves #913 - fix problems when copying objects in world editor

- controllers/graphController.js
- test/integration/graph-save.js
In anticipation of having to do some batch processing at a later stage.
> Store the original unmodified image as well

- browser/scripts/worldEditor/worldEditor.js
also make the grid follow the vr camera again
> Resolves #1193 - make radial grid the default

- controllers/graphController.js
- lib/graphAnalyser.js
- models/graph.js
- test/controllers/graph.js
- test/fixtures/loaders.json
- test/integration/graph-save.js
- test/unit/graphAnalyser.js
> analyse size and number of assets from graph; resolves #1237

- browser/scripts/ui-site.js
browser-sniffed classes on body
> resolve #657 - browser-sniffed css classes on body

- browser/plugins/slider_float_generator.plugin.js
- less/editor.less
- views/server/partials/editorSvgSprite.handlebars
> resolve #1268, resolve #352 - update slider node

- browser/scripts/screenshot/ScreenshotRenderer.js
> Resolves #1302 - take screenshots in double resolution and scale down with antialiasing

- browser/plugins/three_material_lambert.plugin.js
- browser/plugins/three_material_phong.plugin.js
default to white rather than undefined colour
> Resolves #1257 - disconnecting colour input no longer makes material black

- browser/plugins/three_mesh.plugin.js
- browser/scripts/abstractObjectGazePlugin.js
- browser/scripts/application.js
- browser/scripts/node-ui.js
- browser/scripts/subGraphPlugin.js
- browser/test/fixtures/subGraphCutUndo.json
- browser/test/integration/helpers.js
- browser/test/integration/subGraphCutUndo.js
output proxy's arrayness was set incorrectly on undo cut
> Resolves #1256, resolves #1258 - fix for undoing an object3d removal in subgraph

- browser/plugins/three_group.plugin.js
- browser/scripts/core.js
- browser/vendor/borismus/webvr-manager.js
- browser/vendor/three/CardboardEffect.js
- Take devicePixelRatio into account in CardboardEffect
> Release 20160218 part 2

- browser/plugins/camera_forward_vector.plugin.js
- browser/plugins/plugins.json
- documentation/browser/plugins/camera_forward_vector.md
This is required for feeding camera parameters into a near-distance-field vr shaders
> add a plugin to extract camera forward direction

- browser/vendor/borismus/webvr-manager.js
a.k.a fix wrong place for custom event
> fix the webvrmanager fix that required disabling by player fix

- browser/scripts/application.js
- browser/scripts/ui-core.js
- browser/scripts/worldEditor/worldEditor.js
- browser/scripts/worldEditor/worldEditorCameraSelector.js
- browser/test/integration/pluginDocs.js
- controllers/documentationController.js
- test/controllers/documentationController.js
add a failure case test for docs and improve error messaging
> Improve plugin docs tests

- browser/scripts/threesixty.js
- less/threesixty.less
- views/graph/show.handlebars
also restores animated header buttons
> 360: style view in vr dialog

- browser/scripts/application.js
cut/copy/paste event handlers check if event is relevant
> resolve #1367, resolve #1368 cut-copy-paste and text boxes

- controllers/graphController.js
- models/graph.js
- services/graphService.js
- test/integration/graph-save.js
- allows (only) the owner to edit it still
> allow disabling editing in graph model; resolves #1446

- less/editor_shell.less
- less/editors.less
- views/layouts/editor.handlebars
> resolve #762 - switch code display font to source code pro

- browser/scripts/collapsible-select-control.js
- less/editor.less
> #1161 - fix preset/object list unwanted scroll when dragging out item

- browser/plugins/plugins.json
- browser/plugins/three_object3d_bbox_extractor.plugin.js
- documentation/browser/plugins/three_object3d_bbox_extractor.md
> add bbox extractor plugin

- .gitignore
- browser/embed.html
- browser/scripts/embed.js
- browser/scripts/ui-site.js
- browser/scripts/ui/playerUI.js
- less/homepage.less
- less/playerpage.less
- less/site.less
- views/graph/show.handlebars
- views/partials/playerShareDialog.handlebars
- views/server/partials/home/howItWorks.handlebars
- resolves #1507 - multiple embeds
- resolves #1502 - correct code in dialog, 
- also collapse embed code
- also resolves #1508 - homepage tutorial link
- other minor fixes and tweaks
> player fixes and tweaks

- browser/vendor/borismus/webvr-polyfill.js
see https://github.com/borismus/webvr-polyfill/issues/80
> fixes #1491 until an official fix (DeviceMotion in embedded Android Chrome)

- browser/scripts/ui/uiAbstractProperties.js
- browser/scripts/ui/uiPropertiesObj3d.js
- browser/scripts/ui/uiProxyVec3.js
- less/libraries.less
- resolves #1526 - scale correctly in linked mode
- resolves #1527 - undo resets scaleLinked
- refine value entry
- recover from edge case where (scale) xyz is linked and xyz=0.0
> properties panel bugfix and refinement

- README.md
I joined this project today and came across a few minor issues when installing.  I made a few small tweaks to the README to help other new joiners.
> Update readme - add suggested node version and remove npm run setup step

- browser/scripts/editorChannel.js
- browser/scripts/player.js
- browser/test/functional/features/editor.feature
- browser/test/functional/features/fork.feature
- browser/test/functional/features/publish.feature
- browser/test/functional/steps/given.js
- browser/test/functional/steps/then.js
- browser/test/functional/steps/when.js
- browser/test/functional/support/action/signIn.js
- browser/test/functional/support/action/waitForEditor.js
- browser/test/functional/support/check/checkNodeCount.js
- browser/test/functional/support/check/waitForFork.js
- browser/test/functional/support/check/waitForPlayer.js
> add a browser functional test for publish

- app.js
- browser/scripts/application.js
- browser/scripts/wschannel.js
- views/layouts/main.handlebars
- views/layouts/player.handlebars
- views/layouts/threesixty.handlebars
- also fix startup speed in production by not using scripts via connect-assets
> use secure Web Socket connections, fixing proxy issues

- browser/style/threesixty.css
- less/playerpage.less
- views/graph/show.handlebars
> banner image on embeds

- browser/plugins/three_webgl_renderer.plugin.js
- browser/scripts/webVRAdapter.js
> size correctly on init

- browser/scripts/threeObject3dPlugin.js
> Revert "object3d scaling should multiply, not add to graph input"

- browser/scripts/webVRAdapter.js
when page loaded in landscape orientation and then the user touches and
drags down and quickly up, sometimes iOS repaints to the wrong
dimensions _after_ we’ve resized our target. the webvradapter schedules
one additional check on iOS for this condition and forces a resize to
the available dimensions.
> fix initial sizing, fix erroneous sizing on iOS

- browser/scripts/threeObject3dPlugin.js
> Revert "Revert "object3d scaling should multiply, not add to graph input""

- browser/plugins/three_webgl_texture_renderer.plugin.js
> TextureRendererPlugin - do not mangle pixelRatio

- browser/plugins/member_to_float_modulator.plugin.js
- browser/plugins/plugins.json
- browser/plugins/radial_point_geometry.plugin.js
- browser/plugins/three_group.plugin.js
- browser/plugins/three_point_cloud_material.plugin.js
- browser/plugins/url_stereo_latlongmap_generator.plugin.js
- browser/scripts/abstractObjectGazePlugin.js
- documentation/browser/plugins/radial_point_geometry.md
- documentation/browser/plugins/url_stereo_latlongmap_generator.md
- fix object member to float
- add stereo lat long map plugin
- change default point cloud colour to white
- fix gaze clicker counting in nested groups
> Usability fixes

- browser/vendor/three/OBJLoader.js
- rather display a model with some elements missing than nothing at all
> ignore unsupported lines

- views/presets/presets.handlebars
> suppress autocorrect on preset search

- browser/scripts/embed.js
> fix embed sizing vs orientationchange

- browser/scripts/collapsible-select-control.js
- browser/scripts/preset-manager.js
- browser/style/threesixty.css
- less/core.less
> fix presets collapsing

- browser/plugins/three_loader_scene.plugin.js
- browser/plugins/three_webgl_renderer.plugin.js
- browser/scripts/glTFUtils.js
- browser/scripts/loaders/modelLoader.js
- browser/scripts/loaders/multiObjectLoader.js
- browser/scripts/loaders/sceneLoader.js
- browser/scripts/stores/graphStore.js
- browser/scripts/ui-upload.js
- browser/scripts/worldEditor/abstractWorldEditorHelperObject.js
- browser/scripts/worldEditor/boundingSphereHelper.js
- browser/scripts/worldEditor/skeletonHelper.js
- browser/scripts/worldEditor/worldEditor.js
- browser/vendor/three/loaders/ColladaLoader2.js
- browser/vendor/three/loaders/FBXLoader.js
- browser/vendor/three/loaders/gltf/glTF-parser.js
- browser/vendor/three/loaders/gltf/glTFAnimation.js
- browser/vendor/three/loaders/gltf/glTFLoader.js
- browser/vendor/three/loaders/gltf/glTFLoaderUtils.js
- browser/vendor/three/loaders/gltf/glTFShaders.js
- browser/vendor/three/loaders/gltf/gltfUtilities.js
- browser/vendor/three/three.js
- controllers/sceneController.js
- gulpfile.js
- lib/imageProcessor.js
- lib/sceneProcessor.js
- views/layouts/editor.handlebars
Mileage will vary but these are mostly working now.
glTF tested with all three.js test glTF assets, 3 out of 4 work perfectly, 1 (monster.gltf) has problems with bounding volume
known problems:
- glTF animation doesn't respect vizor pausing 
- some glTF models report incorrect bounding sphere
> Resolves #1496, resolves #969 - glTF + FBX + Collada loading

- controllers/home.js
- package.json
- views/server/partials/home/homeFeatured.handlebars
also updates express handlebars to v4 (inline templates)
> rotate featured scenes on the homepage

- browser/postMessage.html
> update postMessage.html to current embed code

- browser/plugins/cubemap_assembler.plugin.js
- browser/plugins/plugins.json
- browser/plugins/three_material_phong.plugin.js
- browser/plugins/three_material_standard.plugin.js
- browser/plugins/url_cubemap_generator.plugin.js
- browser/plugins/url_stereo_cubemap_generator.plugin.js
- documentation/browser/plugins/cubemap_assembler.md
- documentation/browser/plugins/three_material_phong.md
- documentation/browser/plugins/url_cubemap_generator.md
add envmap input to phong material
add a plugin to load mono cubemaps
add a plugin to assemble a cubemap out of six individual textures
> Resolves #1428 - fix env map

- browser/scripts/application.js
- browser/scripts/ui-site.js
makes the notification mechanism available to the entire site
> move growl() out and make global

- controllers/imageController.js
- lib/imageProcessor.js
- modelRoutes.js
- models/user.js
- test/integration/avatars.js
- test/integration/headers.js
refactors and extends imageProcessor to use a common call for uploading headers as well as avatars
> allow uploading of profile headers

- app.js
- controllers/graphController.js
- controllers/presetController.js
- lib/templateCache.js
- npm-shrinkwrap.json
graphController attempts to recompile the template cache if in development mode, but is missing the correct configuration. making templateCache global for a concise fix.
> fix template cache failing to recompile

- browser/scripts/threesixty.js
- less/core.less
- less/editor_shell.less
- less/playerpage.less
- less/site.less
- less/threesixty.less
- views/partials/controls/svgButton.handlebars
- views/partials/controls/svgLink.handlebars
- views/server/partials/siteSvgSprite.handlebars
> add TOS link to 360 site, resolves #1734

- browser/vendor/three/three.js
- package.json
- Match world editor and VR camera far planes
- Only allow scaling in local space
> Release 20160714 - 0.12.1

- browser/scripts/ui-site.js
- browser/scripts/ui/xhrForm.js
- bugfix for not removing loading class on form after receiving response
- xhrform stores last result&status in form’s dataset to allow more flexible CSSing
- cleaned up generic page initialisation in ui-site
> xhrform bugfixes & refinements

- browser/scripts/ui-site.js
- lib/hbs-helpers.js
- views/partials/assets/graphCardJS.handlebars
.. since that isn’t essential and may be unavailable
> make graphcard json fail gracefully with no creator profile data

- browser/scripts/chat.js
- lib/editorChannelServer.js
- views/editor.handlebars
adds maxlength to editor chat input, trims input before checking for value, resolves #1862
> editor chat input maxlength and trim

- models/user.js
- views/server/partials/home/_header.handlebars
- views/server/partials/userpage/nav.handlebars
- resolves background repeating when changing any account details
- adds createdAt date to public userpage header
> minor fixes to profile header

- bin/test-functional.sh
- browser/scripts/ui/ui-helpscreen.js
- browser/test/functional/features/helpscreen.feature
- tools/create-test-examples.js
resolves #1909 - Examples list is empty
> fix missing examples in Help screen

- browser/plugins/url_video_generator.plugin.js
- browser/plugins/video_player.plugin.js
- browser/scripts/core.js
- browser/scripts/graph.js
- browser/scripts/loaders/assetLoader.js
- browser/scripts/loaders/videoLoader.js
- browser/scripts/player-run.js
- browser/scripts/player.js
- browser/scripts/ui/playerUI.js
- browser/scripts/webVRAdapter.js
- browser/test/unit/playerUI.js
- common/graphAnalyser.js
- controllers/graphController.js
- gulpfile.js
- less/core.less
- less/playerpage.less
- models/graph.js
- services/graphService.js
- tools/pull.js
- views/graph/show.handlebars
- views/layouts/editor.handlebars
- add READY state to Player and a button in UI.
- refactor PlayerUI state management
- add `hasVideo` to Graph
- adds a new `VideoLoader` asset loader
> Fix Video playback on Android; resolves #1838

- browser/scripts/ui-site.js
> fix popovers

- browser/plugins/variable_local_read.plugin.js
- browser/plugins/variable_local_write.plugin.js
- browser/plugins/variable_local_write_conditional.plugin.js
- browser/test/fixtures/variables.json
- browser/test/integration/helpers.js
- browser/test/integration/variables.js
- package.json
- Fix issue with Variables disconnecting
> Release 20170126 - v0.14.16

- app.js
- browser/plugins/url_audio_buffer_generator.plugin.js
- browser/scripts/file-select-control.js
- browser/scripts/loaders/audioBufferLoader.js
- browser/scripts/util.js
- browser/vendor/three/OBJLoader.js
- controllers/assetController.js
- lib/streamFile.js
- modelRoutes.js
- package.json
also: allow loading to finish if decodeAudioData fails
> Support switching between ogg and m4a (iOS) depending on platform

- browser/plugins/three_webgl_renderer.plugin.js
- browser/scripts/application.js
- browser/scripts/loaders/assetLoader.js
- browser/scripts/loaders/modelLoader.js
- browser/scripts/patchManager.js
- config/config.js
- controllers/patchController.js
- lib/cloudStorage.js
- package.json
- services/graphService.js
- test/integration/patch-save.js
- views/filebrowser/patch.handlebars
- use the new URL for graph model when saving
- use user patches via redirect to CDN
- use vizor/system patches from CDN
- fix issue with loading CORS images from ModelLoader
> fixes for cloud-patches 

- browser/plugins/url_texture_generator.plugin.js
- browser/scripts/loaders/assetLoader.js
- browser/test/unit/assetLoader.js
- package.json
Manually setting `urllow` in a specific experience for now
> Hotfix Hack: support for loading low-res versions of textures on iOS

- less/build_vizor2teaser.less
- views/vizor2Teaser.handlebars
> Add a “We’re hiring” hover balloon to Jobs link in footer

- views/patch_editor/help_shortcuts.handlebars
Zero VR Cam -> Zero VR Camera
Orthographic Cam -> Orthographic Camera
Helper -> Toggle Helpers
Local Handles -> Toggle Local Handles
> Un-abbreviated some Keyboard Shortcuts

- browser/test/functional/steps/when.js
- package.json
updates webdriver devDependencies and fixes failing steps.
tested with Chrome 60
> fix broken webdriver

- views/vizor2Teaser.handlebars
Added https://www.dropbox.com/sh/qj6qu4rwmvsp0e1/AAAPaKeK12xZZbqKXo3cok_ia?dl=0 to teaser page
> Add Press Kit to Teaser Page

- browser/scripts/webVRAdapter.js
- browser/test/functional/support/action/openEditor.js
- browser/test/functional/support/action/waitForEditor.js
- documentation/browser/plugins/animate_float_on_trigger.md
- Fix resolution in GearVR/Oculus Browser
> Release 20171205

- WindowsInstallationReadme.md
This PR adds installation instructions (tested on Windows 10) as a separate .md file in the root of the repository. After uploading the file, good idea would be to add a link to it in README.md.
> Add instructions on running Patches locally on Windows (#2083)

- browser/patches/_template-360-photo.json
Simplified template, more access to parameters, etc. Less nested patches. Removed Gaze clicker.
> 360.vizor.io: Removed Gaze Clicker + simplified template + now with FOV/width+height segments + radius control directly in the root of the patch.
